diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
core.editor="C:\Users\avril\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
safe.directory=D:/Development/paginaweb
safe.directory=D:/Development/airbnb-clone
credential.helper=manager-core
user.name=gustavo-avril
user.email=36135271+gustallafermrd@users.noreply.github.com
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
lfs.repositoryformatversion=0
remote.origin.url=git@github.com:gustallafermrd/mipueblo.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
